apiVersion: nas-csi.dev/v1alpha1
kind: ClusterIntent

profile: maintenance-basic

nodes:
  servers: 1
  agents: 2

storagePolicies:
  - name: repos-dev
    access: read-write
    workload: git-repositories
  - name: samples-ro
    access: read-only
    workload: streaming-library

addons:
  nasCsi: true
  metricsServer: true

applications: []
