[package]
name = "nas-csi-node-plugin"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nas-csi-proto = { path = "../csi-proto" }
nas-csi-types.workspace = true
serde_json.workspace = true
serde_yml.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
