apiVersion: v1
kind: PersistentVolume
metadata:
  name: repos-existing
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-csi-existing
  csi:
    driver: nas-csi.dev
    volumeHandle: repos
    volumeAttributes:
      nas-csi.dev/dataset: tank/repos
      nas-csi.dev/sourcePath: /mnt/tank/repos
      nas-csi.dev/policy: repos-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repos-existing
  namespace: default
spec:
  storageClassName: nas-csi-existing
  volumeName: repos-existing
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
